// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-5FqdUDwcQvE09-7KaNBgBiWLgB0qdNs',
    appId: '1:565789835581:web:d5d9a9a0e3629f16138554',
    messagingSenderId: '565789835581',
    projectId: 'todo-app-51a38',
    authDomain: 'todo-app-51a38.firebaseapp.com',
    storageBucket: 'todo-app-51a38.firebasestorage.app',
    measurementId: 'G-25VNLC4TL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxhJbNQdmrZ2FlwmO4L87wu5i5Ydgxqak',
    appId: '1:565789835581:android:6fc6892bba40b59b138554',
    messagingSenderId: '565789835581',
    projectId: 'todo-app-51a38',
    storageBucket: 'todo-app-51a38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuOx3sUnZqAC7pKWYBWh_NVe7XOXpzKd0',
    appId: '1:565789835581:ios:11258dd445cf2be2138554',
    messagingSenderId: '565789835581',
    projectId: 'todo-app-51a38',
    storageBucket: 'todo-app-51a38.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuOx3sUnZqAC7pKWYBWh_NVe7XOXpzKd0',
    appId: '1:565789835581:ios:11258dd445cf2be2138554',
    messagingSenderId: '565789835581',
    projectId: 'todo-app-51a38',
    storageBucket: 'todo-app-51a38.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-5FqdUDwcQvE09-7KaNBgBiWLgB0qdNs',
    appId: '1:565789835581:web:8ba9d353f49b1d15138554',
    messagingSenderId: '565789835581',
    projectId: 'todo-app-51a38',
    authDomain: 'todo-app-51a38.firebaseapp.com',
    storageBucket: 'todo-app-51a38.firebasestorage.app',
    measurementId: 'G-BG10NL5SDR',
  );
}
